# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc6322238622bee5c0e4b450e9f3e72cbbe366954ba2e80cd50acc6cbf9c5f68ae1f95326326cc0e32ed9dc8e997623ebb5b7135b9a27075e025bb642a51256

test:
  secret_key_base: 136041b4e95ef427567477120c5996f7273d62bccd64fc6d3b47155b765e1b907995842a50f0093148aa93889b033d7efed45ce7b6e8b7047d995cd0a9919446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
